# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
%matplotlib inline

# Import DataSet

In [3]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [4]:
print(X,y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]] [1 0 1 ... 1 1 0]


# Data Preprocessing

## Applying Label Encoder

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [6]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

## Applying One Hot Encoder

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)


## Split data set into training and test set

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [11]:
print(X_train,X_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]] [[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Building The ANN

## Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

## Adding the input layer and first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding 2nd hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding output layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

# Training the ANN

## Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

## Training ANN with training set

In [17]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 160us/sample - loss: 0.5218 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4622 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4414 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4314 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4250 - accuracy: 0.7990
Epoch 6/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.4198 - accuracy: 0.8138
Epoch 7/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.4148 - accuracy: 0.8198
Epoch 8/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4087 - accuracy: 0.8211
Epoch 9/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4026 - accuracy: 0.8240
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 74us/sample - loss: 0.3381 - accuracy: 0.8611
Epoch 78/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3381 - accuracy: 0.8621
Epoch 79/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.3385 - accuracy: 0.8618
Epoch 80/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3381 - accuracy: 0.8622
Epoch 81/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3382 - accuracy: 0.8630
Epoch 82/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3376 - accuracy: 0.8640
Epoch 83/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3376 - accuracy: 0.8608
Epoch 84/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.3375 - accuracy: 0.8624
Epoch 85/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3381 - accuracy: 0.8621
Epoch 86/100
8000/8000 [==========================

# Prediction

## Predicting a random value

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


## Predicting Test set

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confussion Matrix

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1520   75]
 [ 206  199]]


0.8595